### ISSUE TITLE
Installing from sources doesn't seems to work on CentOS 7

### ISSUE THREAD

**Issue by avoinea** [gondor/docker-volume-netshare#1]
```
$ ./docker-volume-netshare --verbose nfs
$ docker run -it --rm --volume-driver=nfs -v 10.0.0.23/mnt/vdb1:/media/ busybox sh
```
```
Error response from daemon: no such file or directory
```

If I manually create `/var/lib/docker-volumes/netshare/nfs/10.0.0.23/mnt/vdb1`, then I get the following error:

```
Error response from daemon: Cannot start container 33017f3737c548eab65d603f721d89bc2a843b72c7fa9081d04cbbd93efb8af8: Plugin Error: {"Mountpoint":"","Err":"exit status 32"}
```

Docker version `1.8.2`

**Comment by gondor** [comment]
Is the driver being launched as a root?  I haven't tested on CentOS 7 so may need to startup a VM.  I have validated on AWS ECS Optimized AMI which is a spawn of RHEL and had no issues.

**Comment by avoinea** [comment]
Ok. My fault, I didn't have `nfs-utils` installed. You should add it as dependency within `README > Launching in NFS mode` section as it is a host dependency.

```
DEBU[0003] exec: mount -t nfs4 10.0.0.23:/mnt/vdb1/ /var/lib/docker-volumes/netshare/nfs/10.0.0.23/mnt/vdb1
 
2015/11/04 16:50:19 mount: wrong fs type, bad option, bad superblock on 10.0.0.23:/mnt/vdb1/,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

Also I still get this error when I try to create my container:
```
Error response from daemon: no such file or directory
```

if the path on host `/var/lib/docker-volumes/netshare/nfs/10.0.0.23/mnt/vdb1` doesn't exist. I have to manually create it before container creation. And the tricky part is that `vdb1` folder is removed by the plugin on `docker rm -v my-container`, which I think is OK, but I also think that it should be automatically created by the plugin.

**Comment by gondor** [comment]
Great idea on adding to the README.  As far as the creation thats what is baffling me.  It's suppose to be and in all my test environments it is.  That is why I was asking if your running it at root.   

Are you running the plugin from Go source or a downloaded binary?  If it's source I could add a little more to the verbose logging where it would normally create the directory.

**Comment by avoinea** [comment]
Same behavior with binary (**docker-volume-netshare_0.5_linux_amd64**) and source.

**Comment by gondor** [comment]
Ok appreciate all the info.  I just ran a test using NFS on my Ubuntu setup and it did work fine.  My original tests didn't test the "/mnt/dir" like you were doing so thought maybe thats where the bug was.  Unfortunately it worked without problems.  

For your interest my test on Ubuntu:
```
docker run -it --volume-driver=nfs -v 10.238.196.214/mnt/testme:/data ubuntu /bin/bash
```
To verify I added a README in the testme directory prior to running the container.  I also make sure the /var/lib/docker-volume-netshare/* didn't exist.  Everything mounted and the /data in ubuntu docker had the README.

I'm going to have to diagnose Go on CentOS 7 at this point to see if the LStat on checking if the directory exists is returning the proper expected case.

**Comment by gondor** [comment]
Are you using any different storage drivers with the Docker daemon?  I couldn't reproduce this on CentOS.

Steps:
1. Launched a CentOS 7 AMI in AWS
2. Turned of SELinux
3. Installed nfs-utils
4. Downloaded and ran the docker daemon 1.8.2
5. Ran the volume plugin as root
6. Launched an ubuntu container using the volume driver reference and a mount point of /mnt/testme (mount on the remote NFS share)
7. Verified the directory and contents were mounted in Ubuntu

This was on a brand new instance and worked first try using the default storage driver in the daemon vs using AUFS, LVM custom storage options.

**Comment by avoinea** [comment]
I added some logging and it fails after this message:
```
DEBU[0002] Path for 10.0.0.23/mnt/vdb1 is at /var/lib/docker-volumes/netshare/nfs/10.0.0.23/mnt/vdb1
```

For me it seems that docker is trying to get the Path before the Mount (as the logs from nfs > Mount are not displayed) and it crash with:

```
Error response from daemon: no such file or directory
```

**Comment by gondor** [comment]
@avoinea This is great and I appreciate you digging into this since I am unable to reproduce it.  Have you added debug to the `Create` call?  You could attempt create the local directory in the create so it exists and then when mount is called it would skip the check since it's already present.    

I have a feeling this may solve it and it may be differences in the daemon with different OS/Storage drivers.

**Comment by avoinea** [comment]
https://gist.github.com/avoinea/3b66add292d0242251bf

***$ ./docker-volume-netshare --verbose=true nfs***
```
DEBU[0002] Creating volume 10.142.71.23/mnt/vdb1
       
2015/11/05 16:53:45 AAAA
2015/11/05 16:53:45 /var/lib/docker-volumes/netshare/nfs/10.142.71.23/mnt/vdb1
2015/11/05 16:53:45 BBBB
DEBU[0002] Path for 10.142.71.23/mnt/vdb1 is at /var/lib/docker-volumes/netshare/nfs/10.142.71.23/mnt/vdb1
 
2015/11/05 16:53:45 AAAA
2015/11/05 16:53:45 /var/lib/docker-volumes/netshare/nfs/10.142.71.23/mnt/vdb1
2015/11/05 16:53:45 BBBB
INFO[0002] CCC                                          
INFO[0002] {/var/lib/docker-volumes/netshare/nfs/10.142.71.23/mnt/vdb1 }
```

***$ docker run -it --rm --volume-driver=nfs -v 10.142.71.23/mnt/vdb1:/media/ busybox sh***
```
Error response from daemon: no such file or directory
```

**Comment by avoinea** [comment]
Maybe we can speed this up by talking on irc #docker channel.

**Comment by gondor** [comment]
You could try adding this code to the `Create` call first as a quick local test.

```
dest := mountpoint(n.root, r.Name)
if err := createDest(dest); err != nil {
		return dkvolume.Response{Err: err.Error()}
}
```
The above will resolve the destination directory and then call `createDest` which will create the local directory if it doesn't exist.

It will at least rule out that we should be Creating the local directory prior to the Mount func being called.

**Comment by avoinea** [comment]
Yap, that works:

```
func (n nfsDriver) Create(r dkvolume.Request) dkvolume.Response {
+       dest := mountpoint(n.root, r.Name)
+       if err := createDest(dest); err != nil {
+               return dkvolume.Response{Err: err.Error()}
+       }
        return dkvolume.Response{}
 }
```
