### ISSUE TITLE
Need to mount on host?

### ISSUE THREAD

**Issue by patrick-bark** [gondor/docker-volume-netshare#10]
Hey, this doesn't seem to be working for me with NFS. The one step I am unclear on is: does this need to be mounted on the host first, then shared as a volume? or in the -v option, am I giving a network path? Thanks

**Comment by gondor** [comment]
What OS are you testing this on?  What Docker version are you using?

**Comment by patrick-bark** [comment]
I'm using ubuntu 12.04, and docker 1.9.1. To be clear I have the drive mounted on the host os and am trying to share that with the docker container. Is that the right pattern?

**Comment by TomaszKorwel** [comment]
No. You don't have to mount the share on the host, you pass the parameters to the docker run command and it mounts nfs share directly within the container.
