### ISSUE TITLE
On boot2docker permission denied to docker daemon

### ISSUE THREAD

**Issue by blaggacao** [gondor/docker-volume-netshare#14]
I can see this error massage when trying out your plugin on boot2docker. It seems the docker user is not authorized to chown the mounted volume.
```
$ docker run -u root -ti -v 192.168.0.66/flct:/home busybox
docker: Error response from daemon: chown /var/lib/docker-volumes/netshare/cifs/192.168.0.66/flct: permission denied.
```
```
docker@dev:~$ ls -la /var/lib/docker-volumes/netshare/cifs/192.168.0.66/flct/
total 4
drwxr-xr-x    2 root     root          4096 Feb 29 21:33 ./
drwxr-xr-x    3 root     root            60 Feb 29 21:37 ../
drwxr-xr-x    2 root     root             0 Feb 29 21:33 deploy/
drwxr-xr-x    2 root     root             0 Feb 29 21:33 o9/
```

Any ideas about it?

**Comment by blaggacao** [comment]
See also issue, I think your plugin is a hot candidate to solve this long standing problem... https://github.com/boot2docker/boot2docker/issues/1145

**Comment by blaggacao** [comment]
An output, while sorting this out, might be useful:
```
docker@dev:~$ mount -t cifs
//192.168.0.66/flct on /var/lib/docker-volumes/netshare/cifs/192.168.0.66/flct type cifs (rw,relatime,vers=1.0,cache=strict,username=David,domain=WORKGROUP,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.0.66,file_mode=0755,dir_mode=0755,nounix,serverino,mapposix,rsize=61440,wsize=65536,actimeo=1)
```

**Comment by blaggacao** [comment]
Unfortunately, I'm not a go expert, else I would just try and supply a fix, but I guess, if in the cifs driver, a small routine which checks the docker daemon user and sets the `uid`,`gid`,`forceuid` and `forcegid` options accordingly would be superbe. Also a rw, specification on the command line would be nice, as I saw it's always put to `rw`...

**Comment by so0k** [comment]
How did you start the docker-volume-netshare driver?

**Comment by blaggacao** [comment]
Hm, I guess I have had a configuration issue, I apologize. It worked now.
