### ISSUE TITLE
Volume names conflict with Swarm

### ISSUE THREAD

**Issue by so0k** [gondor/docker-volume-netshare#16]
I created a swarm cluster and loaded the docker-volume-netshare driver on each node.

Works:

1. Set docker cli to node0, run `docker volume create -d cifs --name 192.168.233.1/demo`. 
2. Set docker cli to node1 and repeat the same command as above. 
3. Set docker cli to master0 --swarm and run 2 containers with `-v `192.168.233.1/demo:/demo`
4. You now have 2 containers sharing a volume across the swarm cluster

Error:

1. If I run the `docker volume create -d cifs --name 192.168.233.1/demo` against the swarm I get the following message:

```
unable to find a node that satisfies node==192.168.233.1
```

Any suggestions? Maybe the naming scheme needs to be revised?

**Comment by gondor** [comment]
Ok, this seems to be a parsing error in the actual volume flag when using swarm.

I setup a swarm cluster and got it work work by prefixing a / in front of the ip address.

I tested with NFS (previously could reproduce what you were seeing).

Example:
```
# add / in front
docker volume create -d cifs --name /192.168.233.1/demo
# when mounting - dont add /
docker run -i -t --volume-driver=cifs -v 192.168.233.1/demo:/somewhere ubuntu /bin/bash
```

**Comment by so0k** [comment]
Great, thanks for solution - I will need to test further

**Comment by deviantony** [comment]
Yeah, add the same issue. A section about this could be added in the README.
