### ISSUE TITLE
Systemd .service file

### ISSUE THREAD

**Issue by ahmetalpbalkan** [gondor/docker-volume-netshare#17]
Do you have a systemd .service file that properly starts before/after docker.service that I can reuse? It sounds like this project can distribute one as I imagine most people would be repeating that step over and over.

**Comment by gondor** [comment]
This used to be part of the packaging but I think a recent PR broke it.  You can grab what you need (deb or enterprise) from https://github.com/gondor/docker-volume-netshare/tree/master/support

**Comment by ahmetalpbalkan** [comment]
Ah thank you. Totally missed it.
