### ISSUE TITLE
NFS driver not working as expected

### ISSUE THREAD

**Issue by garrettux** [gondor/docker-volume-netshare#20]
Hi, I'm using the NFS driver, and it doesn't seem to be working as expected.  I end up with the NFS share mounted on the host, but not in the container.  I'm wondering if I'm missing something, or if you can help shed any light.

Here's what I'm seeing.  I start docker-volume-netshare:
```
/usr/bin/docker-volume-netshare nfs --verbose
```

then start a container:
```
# docker run -d --volume-driver=nfs -v nfshost.mycompany.com/vol/docker:/nfs ubuntu sleep 1000000
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
203137e8afd5: Pull complete
2ff1bbbe9310: Pull complete
933ae2486129: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:1bea66e185d3464fec1abda32ffaf2a11de69833cfcf81bd2b9a5be147776814
Status: Downloaded newer image for ubuntu:latest
4964d28b520ba95ed2f84438466fa1050cd009924b9f3c155e130dd9ccdd1e58
```
 I can see the NFS share mounted on the host, and some test files inside:
```
# df -h -t nfs4
Filesystem                             Size  Used Avail Use% Mounted on
nfshost.mycompany.com:/vol/docker   70G   32M   70G   1% /var/lib/docker-volumes/netshare/nfs/nfshost.mycompany.com/vol/docker

# ls -al /var/lib/docker-volumes/netshare/nfs/nfshost.mycompany.com/vol/docker
total 8
drwxrwxrwx. 2 nobody nobody 44 Mar 21 15:44 .
drwxr-xr-x. 3 root   root   28 Mar 22 15:59 ..
-rw-r--r--. 1 nobody nobody  5 Mar 18 19:30 foo
-rw-r--r--. 1 nobody nobody  0 Mar 18 19:57 foo3
-rw-r--r--. 1 nobody nobody 10 Mar 18 20:15 index.html
```

But in the container, it's not mounted via NFS, and there's nothing in the directory:
```
# docker exec -it 4964d28b520b bash
root@4964d28b520b:/# df -h
Filesystem                                                                                           Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:0-184731912-514559fcad3a7c536330104cdc768b5b6d552ceb6fac041d8ebd9688af3eca8d   10G  240M  9.8G   3% /
tmpfs                                                                                                3.9G     0  3.9G   0% /dev
tmpfs                                                                                                3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/mapper/centos-root                                                                               38G   13G   26G  34% /nfs
shm                                                                                                   64M     0   64M   0% /dev/shm

root@4964d28b520b:/# ls -al /nfs
total 4
drwxr-xr-x.  2 root root    6 Mar 22 15:59 .
drwxr-xr-x. 22 root root 4096 Mar 22 15:59 ..
```

I also noticed the `Mountpoint` from `docker volume inspect` seems wrong:
```
# docker volume ls
DRIVER              VOLUME NAME
nfs                 /var/lib/docker-volumes/netshare/nfs/nfshost.mycompany.com/vol/docker
```

```
# docker volume inspect /var/lib/docker-volumes/netshare/nfs/nfshost.mycompany.com/vol/docker
[
    {
        "Name": "var/lib/docker-volumes/netshare/nfs/nfshost.mycompany.com/vol/docker",
        "Driver": "nfs",
        "Mountpoint": "/var/lib/docker-volumes/netshare/nfs/var/lib/docker-volumes/netshare/nfs/nfshost.mycompany.com/vol/docker"
    }
]
```

Here are the details of my system:

```
# cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)

# uname -a
Linux myserver.company.com 3.10.0-327.3.1.el7.x86_64 #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
# docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64
```

Here's the commit I built docker-volume-netshare from, and I built it against go1.6:
```
docker-volume-netshare mwgarret$ git log -1
commit 3c8ca502e3e857b0638cfdb97e361b25c7d2754f
Author: Jeremy Unruh <jeremybunruh@gmail.com>
Date:   Fri Feb 12 09:50:31 2016 -0800

    Support for Docker 1.10 - Issue #13
```

Thanks for any help you can offer.

**Comment by gondor** [comment]
Ok, thanks for all the detailed info!  I'm adding support to allow a few global options to be specified like ```nfs_port``` on startup and will support more options when using the ```docker volume create methods```.   This will allow you to define some defaults when starting the daemon but still have the flexibility to trump the values for specific endpoints via ```docker volume create```.  Shouldn't take me long to squeeze in.  (hoping next 24 hours)

**Comment by gondor** [comment]
This is odd.  It worked fine for me.

1.  I create two vagrant CentOS 7 machines
2.  Slave 1 - 10.142.142.11 I made the NFS server and exported a share granting Slave 2 full rights
3.  On Slave 2 I tested mounting locally first and it worked.  Added a README, Dropped my mount and tried with Docker

Docker
```
vagrant@slave2 ~]$ docker run -it --rm -v 10.142.142.11/var/nfsshare:/data --volume-driver nfs ubuntu bash
root@dcfece0523bf:/# ls -al /data
total 12
drwxrwxrwx.  2 root root 4096 Mar 21 19:57 .
drwxr-xr-x. 22 root root 4096 Mar 21 20:12 ..
-rw-r--r--.  1 root root   13 Mar 21 19:57 README
```

Logs from Netshare
```
DEBU[0418] Get for 10.142.142.11/var/nfsshare is at /var/lib/docker-volumes/netshare/nfs/10.142.142.11/var/nfsshare
INFO[0418] Mounting NFS volume 10.142.142.11:/var/nfsshare on /var/lib/docker-volumes/netshare/nfs/10.142.142.11/var/nfsshare
DEBU[0418] exec: mount -t nfs4 10.142.142.11:/var/nfsshare /var/lib/docker-volumes/netshare/nfs/10.142.142.11/var/nfsshare
```

Now I'm trying to find differences.  This was tested on Docker 1.10.3

**Comment by garrettux** [comment]
Thanks for looking into it.  I wasn't able to reproduce it in vagrant either.  It seems we've got a weird edge case, or maybe something specific about the way our systems are configured.  Oddly enough, after lots of trial and error and flailing about, we were able to reliably make it work with some very specific steps:

- Starting point is the "failed state," as described above - the NFS share is mounted on the host at this point.
- stop docker and docker-volume-netshare, and delete everything under `/var/lib/docker` and `/var/lib/docker-volumes/` to start with a clean slate, and start the daemons back up:
```
# systemctl stop docker docker-volume-netshare
# rm -Rfv /var/lib/docker*/*
# systemctl start docker docker-volume-netshare
```

- At this point the NFS share is still mounted on the host.  Try to start a new container, and it will fail:
```
# docker run -d --volume-driver=nfs -v nfshost.mycompany.com/vol/docker:/nfs ubuntu sleep 1000000
f296793ee1c86c578636f3632638e53860f9b4b857f6b020c64e65e027c60c65
Error response from daemon: Cannot start container f296793ee1c86c578636f3632638e53860f9b4b857f6b020c64e65e027c60c65: Plugin Error: VolumeDriver.Mount, {"Mountpoint":"","Err":"exit status 32","Volumes":null,"Volume":null}
```

- docker-volume-netshare logs that the share is busy, and it unmounts it:
```
Mar 22 21:25:17 hostname.company.com docker-volume-netshare[10403]: 2016/03/22 21:25:17 mount.nfs4: /var/lib/docker-volumes/netshare/nfs/nfshost.mycompany.com/vol/docker is busy or already mounted
Mar 22 21:25:17 hostname.company.com docker-volume-netshare[10403]: time="2016-03-22T21:25:17Z" level=info msg="Unmounting volume nfsvip01.wdc01np:/vol/docker_registry from /var/lib/docker-volumes/netshare/nfs/nfshost.mycompany.com/vol/docker"
```

- Try to start another container the same way, and this time it works:
```
# docker run -d --volume-driver=nfs -v nfshost.mycompany.com/vol/docker:/nfs ubuntu sleep 1000000
f8ca777e53eb1473a65e2f5024774346e3e9c6569ea1076c14f2cfbbf6f99817
[root@wdc01np-inf-mesos-slave07 ~]# docker exec -it f8ca777e53eb1473a65e2f5024774346e3e9c6569ea1076c14f2cfbbf6f99817 df
Filesystem                                                                                         1K-blocks    Used Available Use% Mounted on
/dev/mapper/docker-253:0-52084039-f8ca777e53eb1473a65e2f5024774346e3e9c6569ea1076c14f2cfbbf6f99817 104805376  245416 104559960   1% /
tmpfs                                                                                                4005608       0   4005608   0% /dev
tmpfs                                                                                                4005608       0   4005608   0% /sys/fs/cgroup
nfshost.mycompany.com:/vol/docker                                                               73364480   32768  73331712   1% /nfs
/dev/mapper/centos-root                                                                             39770112 3622544  36147568  10% /etc/hosts
shm                                                                                                    65536       0     65536   0% /dev/shm
```

I wouldn't really consider this a workaround for us - our use case is that we are running containers on a mesos/marathon cluster, so manual steps to bring up containers isn't a good option.  But, I'm curious if you have any ideas about why it would work properly in this specific scenario.  I'm at a loss :)

**Comment by holgerreif** [comment]
The error message about the busy mount is not logged by docker-volume-netshare but by kernel. 

Just guessing (I don't know the exact workflow at the volume plugin API):
   * docker requests a mount via API
   * plugin tries to mount and fails because the share is actually mounted
   * docker requests umount via API
   * plugin unmounts the nfs share
The seond time call succeds since the volume is not mounted any longer 
As a real workaround you could issue  (as root) the command `umount nfshost.mycompany.com:/vol/docker`

From the docker-volume-plugin perspective it should be checked, whether the nfs mount already exists (destipe the fact that use count `n.mountm.Count(dest)` is zero). If it exists then
   * the plugin should not try to mount the share
   * issue a failure itself (not returning the mount return code 32 "mount failure")
Under same conditions plugin should refuse to unmount a share that is not mounted by itself (HasMount is true, but Count is Zero) and silently ignore the error condition.

Of course, the workaround  in previous comment does not work anymore then, but it is a cleaner behaviour IMHO.

**Comment by gondor** [comment]
Thanks everyone for the feedback.  I'll run some negative tests as your describing (may have to manually make a mount so it exists already) but put some more intelligence in docker-volume-share to understand the mount exists and to utilize it. Same goes for unmounting.  

I will look at the "count" as you described but if it's 0 and I get a mount error I'll use the existing share and increment the count.  Just in case of possible loop holes.

**Comment by holgerreif** [comment]
Well, relying on return code 32 from mounts is now what you want. This return code coud mean everything from "can't resolve hostname" to "share is not exported". 

The only real truth is in `/proc/mounts` where you can check wether the mount is already there.

Please log a warning (not just a debug message) in case you encounter such a situation, since it is a hint that something went wrong.

**Comment by garrettux** [comment]
FWIW I have a vagrant environment where I've been able to consistently reproduce this, and have a control VM where I cannot reproduce it (i.e. it works as expected on the control VM).  The two VMs are CentOS 7, from the exact same base box.

The VM where the plugin works properly has only docker installed, and with the default startup configuration.  The VM where I can reproduce the problem is identical, save two things - it has docker configured to use a cluster backend for overlay networking, and has mesos slave running.  This duplicates our real-world scenario.  Hopefully I can work through these differences and narrow the problem down.

So, I don't know if you'd consider this a bug, or just something on my end, but I'd like to continue to post updates here in case it helps someone else.

One more thing I noticed - in the container on the working VM, `/etc/hosts` is mounted on `/dev/mapper/centos-root`:

```
root@0df1077fb12b:/# df -h
Filesystem                                                                                          Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:0-67593350-c1c32e30b02b6718d52e15f7961ca3aabe38b394159e9c83087458776e636893   10G  240M  9.8G   3% /
tmpfs                                                                                               921M     0  921M   0% /dev
tmpfs                                                                                               921M     0  921M   0% /sys/fs/cgroup
172.28.128.5:/nfs                                                                                    39G  1.5G   37G   4% /nfs
/dev/mapper/centos-root                                                                              39G  1.9G   37G   5% /etc/hosts
shm                                                                                                  64M     0   64M   0% /dev/shm
```

But on the non-working VM, it is not - the nfs directory is, and `/etc/hosts` is not mounted separately at all:

```
root@8476c1b33a4c:/# df -h
Filesystem                                                                                          Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:0-67803339-26d2e272bbfab4ea54ea32b0e007428b98d74746a570f8cba44f5013262624e2   10G  240M  9.8G   3% /
tmpfs                                                                                               921M     0  921M   0% /dev
tmpfs                                                                                               921M     0  921M   0% /sys/fs/cgroup
/dev/mapper/centos-root                                                                              39G  2.2G   37G   6% /nfs
shm                                                                                                  64M     0   64M   0% /dev/shm
```

**Comment by holgerreif** [comment]
This looks strange. Not only `/etc/hosts` has to be mounted but `/etc/hostname` and `/etc/resolv.conf` as well. What is the output of

```
docker inspect --format='MOUNTS: {{.Mounts}}
HOSTS {{.HostsPath}}
HOSTNAME {{.HostnamePath}}
BINDS {{.HostConfig.Binds}}' <your_image>
```
What comes to my mind, that the nfs mount from the docker-volume-netshare plugin fails and the bind mount  to the directory where the host mount should go to (somewhere under `/var/lib/docker-volumes/netshare/`)  does not propagate the mounted nfs share but the directory in the host's root filesystem itself. Maybe then the next mount (for /etc/hosts) fails too?

@gondor: Could you add option "-v" to the nfs mount (nfs.go / func mountVolume) if the plugin is started with `--verbose=true`?

**Comment by garrettux** [comment]
It looks like I was wrong about `/etc/hosts` not being mounted.  It doesn't show up in the output of `df`, but it does show in the output of `mount`:

working VM:
```
[vagrant@localhost vagrant]$ sudo docker inspect --format='MOUNTS: {{.Mounts}}
HOSTS {{.HostsPath}}
HOSTNAME {{.HostnamePath}}
BINDS {{.HostConfig.Binds}}' 7c032802a30a
MOUNTS: [{172.28.128.5/nfs /var/lib/docker-volumes/netshare/nfs/172.28.128.5/nfs /nfs nfs  true rprivate}]
HOSTS /var/lib/docker/containers/7c032802a30a135eba2d7b23e406f64a074e4474e677ab4a50e4156027b46861/hosts
HOSTNAME /var/lib/docker/containers/7c032802a30a135eba2d7b23e406f64a074e4474e677ab4a50e4156027b46861/hostname
BINDS [172.28.128.5/nfs:/nfs]

[vagrant@localhost vagrant]$ sudo docker exec -it 7c032802a30a bash

root@7c032802a30a:/# mount | grep mapper
/dev/mapper/docker-253:0-67499756-41252bfe4c5aaf79a0a397c5d18556d565af1557b4c78ceb9e4feeed586eabe0 on / type xfs (rw,relatime,seclabel,nouuid,attr2,inode64,logbsize=64k,sunit=128,swidth=128,noquota)
/dev/mapper/centos-root on /etc/resolv.conf type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/centos-root on /etc/hostname type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/centos-root on /etc/hosts type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
```

non-working VM:
```
[vagrant@localhost vagrant]$ sudo docker inspect --format='MOUNTS: {{.Mounts}}
> HOSTS {{.HostsPath}}
> HOSTNAME {{.HostnamePath}}
> BINDS {{.HostConfig.Binds}}' 649f072c26d0
MOUNTS: [{172.28.128.5/nfs /var/lib/docker-volumes/netshare/nfs/172.28.128.5/nfs /nfs nfs  true rprivate}]
HOSTS /var/lib/docker/containers/649f072c26d03142cfa16a2d9db0010de4cc7c1c0e130a1476c8ffebacce9955/hosts
HOSTNAME /var/lib/docker/containers/649f072c26d03142cfa16a2d9db0010de4cc7c1c0e130a1476c8ffebacce9955/hostname
BINDS [172.28.128.5/nfs:/nfs]

[vagrant@localhost vagrant]$ sudo docker exec -it 649f072c26d0 bash

root@649f072c26d0:/# mount | grep mapper
/dev/mapper/docker-253:0-67803338-e290f5111f5b56cd58d98965bae5ed2d78156882ed69d15f44ccf02d1536b3e3 on / type xfs (rw,relatime,seclabel,nouuid,attr2,inode64,logbsize=64k,sunit=128,swidth=128,noquota)
/dev/mapper/centos-root on /nfs type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/centos-root on /etc/resolv.conf type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/centos-root on /etc/hostname type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/centos-root on /etc/hosts type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
```

**Comment by garrettux** [comment]
I'm pretty sure i figured out the issue.  On the working VM, we have the default systemd `docker.service` file which sets `MountFlags=slave`.  On the non-working VM (and our mesos cluster), we use chef to install and configure docker, by wrapping the community docker cookbook.  That cookbook drops a service file that contains `MountFlags=private`.  I was able to fix the non-working VM by changing that to slave.

So, it looks like the `MountFlags=private` setting caused us to run into the issue [described here](http://blog.oddbit.com/2015/01/18/docker-vs-privatetmp/) under "Not necessarily the solution".  @holgerreif you were on track about the host's filesystem being propagated instead of the NFS share :)

Thanks for your help guys.

**Comment by gondor** [comment]
Thanks for all the info.  I read about the privatetmp issue (link you added) and my take on that is there isn't a lot we can do from the "docker volume" perspective.   @holgerreif I'll add the -v suggestion you mentioned in the ```mountVolume```.

**Comment by gondor** [comment]
Added Issue #22 regarding the verbose option.
