### ISSUE TITLE
Add verbose logging support during mountVolume func

### ISSUE THREAD

**Issue by gondor** [gondor/docker-volume-netshare#22]
To better debug various environments and distributions the ```mountVolume``` function should log more detailed information when in verbose.

**Comment by gondor** [comment]
Additional debug added to NFS mountVolume call.  In 0.13 release

**Comment by holgerreif** [comment]
Acctually I thought more about passing a `-v` flag to the actuall mount call to get more information about what happend. Means instead of
```
cmd = fmt.Sprintf("mount -t nfs4 -o %s %s %s", opts, source, dest)
```
do the follwoing when verbose flag is given to plugin
```
cmd = fmt.Sprintf("mount -t nfs4 -v -o %s %s %s", opts, source, dest)
```

**Comment by gondor** [comment]
Ok, gotcha thanks

**Comment by gondor** [comment]
Ok, version 0.14 released with verbose support in mount.  Re-open if it doesn't work.  I tested it and am getting the mount feedback now
