### ISSUE TITLE
Add --version flag

### ISSUE THREAD

**Issue by holgerreif** [gondor/docker-volume-netshare#25]
Additionally version should be logged during startup.

**Comment by gondor** [comment]
Ok version 0.15 binary release.

By default the version and build date will be part of help or no args when running.

```
root@default:~# ./docker-volume-netshare
docker-volume-netshare (NFS V3/4, AWS EFS and CIFS Volume Driver Plugin)

Provides docker volume support for NFS v3 and 4, EFS as well as CIFS.  This plugin can be run multiple times to
support different mount types.

== Version: 0.15 - Built: 2016-04-05T11:18:55-07:00 ==

Usage:
.... etc
```

Or you can run ```docker-volume-netshare version``` which would print ```Version: 0.15 - Built: 2016-04-05T11:18:55-07:00```

**Comment by holgerreif** [comment]
One more thing about version: issue a something like
```
docker-volume-netshare Version: 0.15 - Built: 2016-04-05T11:18:55-07:00 starting up with <cmd> <options>
``` 
Otherwise version and help test work fine.

**Comment by holgerreif** [comment]
Works great, everything done.
