### ISSUE TITLE
Unable to start plugin

### ISSUE THREAD

**Issue by testphreak** [gondor/docker-volume-netshare#26]
I am trying to follow the instructions to mount my CIFS share since I am new to this plugin. When I run the command below, I get an invalid group message.
```
service docker-volume-netshare start
chgrp: invalid group: ‘docker’
```
Also, what am I supposed to change for step "Modify the startup options in /etc/default/docker-volume-netshare"? Am I supposed to uncomment this line and pass in the username, password and domain? -

```
## CIFS
#DKV_NETSHARE_OPTS="cifs -u user -p pass -d domain"
```

**Comment by gondor** [comment]
It looks like your starting the plugin as a "non-root" user.  Like the docker daemon this needs to run as root.

**Comment by testphreak** [comment]
Hi Jeremy, I am signed in as root. Even tried with sudo.

```
root@f40fae534f99:/# service docker-volume-netshare start
chgrp: invalid group: ‘docker’
```

**Comment by gondor** [comment]
Can you paste the contents of the systemd or init service that executes docker-volume-netshare.  I've never seen this issue and the code itself doesn't try to chgroup so its something external.  What happens if you execute the binary yourself as root (you can CTRL-C to exec).  ```./docker-volume-netshare cifs -u user -p pass -d domain```

**Comment by testphreak** [comment]
If I try to execute binary as root -
```
root@f40fae534f99:/# ./docker-volume-netshare cifs -u user -p pass -d domain
bash: ./docker-volume-netshare: No such file or directory
```

Install information
```
root@f40fae534f99:/# dpkg -s docker-volume-netshare
Package: docker-volume-netshare
Status: install ok installed
Priority: extra
Section: devel
Maintainer: Jeremy Unruh (https://github.com/gondor) <example@example.org>
Architecture: amd64
Version: 0.15
Description: Docker Volume Plugin - Netshare
```
Here are the contents of systemd and init from the docker container -
Contents of systemd -
```
root@f40fae534f99:/etc/systemd# ls -lrt
total 40
-rw-r--r-- 1 root root 1127 Oct 15 05:01 user.conf
-rw-r--r-- 1 root root  534 Oct 15 05:01 timesyncd.conf
-rw-r--r-- 1 root root 1471 Oct 15 05:01 system.conf
-rw-r--r-- 1 root root  589 Oct 15 05:01 resolved.conf
-rw-r--r-- 1 root root  966 Oct 15 05:01 logind.conf
-rw-r--r-- 1 root root  970 Oct 15 05:01 journald.conf
-rw-r--r-- 1 root root  720 Oct 15 05:01 bootchart.conf
drwxr-xr-x 2 root root 4096 Oct 15 05:01 user
drwxr-xr-x 2 root root 4096 Oct 15 05:01 network
drwxr-xr-x 5 root root 4096 Feb 17 04:49 system
```
Contents of init
```
root@f40fae534f99:/etc/init# ls -lrt
total 44
-rw-r--r-- 1 root root 284 Jul 23  2013 hostname.conf
-rw-r--r-- 1 root root 300 May 21  2014 hostname.sh.conf
-rw-r--r-- 1 root root 363 Jun  5  2014 procps-instance.conf
-rw-r--r-- 1 root root 119 Jun  5  2014 procps.conf
-rw-r--r-- 1 root root 109 May 18  2015 hwclock.sh.conf
-rw-r--r-- 1 root root 444 May 18  2015 hwclock-save.conf
-rw-r--r-- 1 root root 557 May 18  2015 hwclock.conf
-rw-r--r-- 1 root root 534 Jul 20  2015 passwd.conf
-rw-r--r-- 1 root root 352 Oct 15 04:34 udevtrigger.conf
-rw-r--r-- 1 root root 360 Oct 15 04:34 udevmonitor.conf
-rw-r--r-- 1 root root 337 Oct 15 04:34 udev.conf
```

**Comment by testphreak** [comment]
@gondor if it helps this is the docker container I am using - https://github.com/SeleniumHQ/docker-selenium/tree/master/NodeChromeDebug

**Comment by gondor** [comment]
Sorry, didn't know you installed the package.  Remove the ./ before you run the binary.  ie.  ```docker-volume-netshare cifs -u user -p pass -d domain```

Also what OS/Version are you on?

**Comment by testphreak** [comment]
I was running these commands in the container. I may have misunderstood, but are these commands run on the host?

**Comment by gondor** [comment]
Yes, All docker volume based plugins need to run on the host system since they register with the Docker daemon.  

Thats how you can then run your containers using the ```docker run --volume-driver cifs --volume host/share:/container/mount SomeContainer``` etc

The Docker daemon calls the volume plugin who mounts a volume in a tmp directory on the host and links it to the specified directory within the container being run.

**Comment by testphreak** [comment]
Hi @gondor sorry I wasn't able to test it out yesterday as I wasn't at work. Will the commands listed to set up docker-volume-netshare work on a Mac (dpkg isn't available)?

**Comment by gondor** [comment]
No, Docker doesn't run natively on mac.  This has to run where Docker runs which on a mac would be the docker VM.  The docker vm though is pretty slim so you may have to mess around with it to get it to work.
