### ISSUE TITLE
How to use nfs mount option?

### ISSUE THREAD

**Issue by kamihicouki** [gondor/docker-volume-netshare#27]
hi, everyone.
thank's to this project.
i not good english, so, simply state below.

i want to perfomance up nfs client side's.
and, i found the "fscache and cachefilesd"

i tryied add "options" flag into a "/etc/default/docker-volume-netshare" file.
```
## NFS
DKV_NETSHARE_OPTS="nfs --options='-o fsc'"
```

because, standard mount command is this.
```
sudo mount -o fsc NFS_SERVER:/EXPORT_DIR MOUNTPOINT
```

of course, beforehand install and start `cachefilesd `
```
sudo apt-get install cachefilesd
sudo service cachefilesd start
```

and, docker-volume-netshare service restarted.
```
sudo service docker-volume-netshare restart
```

but, not running docker-volume-netshare process.
please, help.

**Comment by gondor** [comment]
Have you tried using the "--options" flag like you have above?  It should work...  You can test it in a different terminal by running docker-volume-netshare in the foreground and in verbose to see how its mounting as you bring up containers in another terminal.  You can run it manually by ```docker-volume-netshare nfs --options='my options' --verbose```

Also, when using the --options flag omit the "-o" since netshare renders that and adds your extra options

**Comment by kamihicouki** [comment]
hi, @gondor .
thanks, reply.

i tried to do immediantely.
```
⟫ sudo docker-volume-netshare nfs --options="-o fsc" --verbose

Usage: 
  docker-volume-netshare nfs [flags]

Flags:
  -v, --version=4: NFS Version to use [3 | 4]. Can also be set with NETSHARE_NFS_VERSION


Global Flags:
      --basedir="/var/lib/docker-volumes/netshare": Mounted volume base directory
      --port=":8877": TCP Port if --tcp flag is true.  :PORT for all interfaces or ADDRESS:PORT to bind.
      --tcp[=false]: Bind to TCP rather than Unix sockets.  Can also be set via NETSHARE_TCP_ENABLED
      --verbose[=false]: Turns on verbose logging

Error: unknown flag: --options
```

**Comment by kamihicouki** [comment]
oh, sorry. (_ _;)

my docker-volume-netshare version was "0.11"
upgrade, version to "0.15" now.

fix.

**Comment by kamihicouki** [comment]
fix
