### ISSUE TITLE
Incorrect systemd unit file

### ISSUE THREAD

**Issue by holgerreif** [gondor/docker-volume-netshare#32]
According to https://docs.docker.com/engine/extend/plugin_api/#systemd-socket-activation the plugin should be started `Before=docker.service`, while this project's unit file has an `After=` ordering.

`Before`ordering makes sense, because the this plugin must be available before docker could start any containers.

Only together with socket activation it could be useful to have an `After` ordering, then one could restart the plugin w/o restarting dockerd. However, when restarting dockerd the plugin is restarted as well and it is not good at maintaining state yet...

**Comment by gondor** [comment]
Thanks for reporting, Feel free to submit a PR with this change if you don't mind.
