### ISSUE TITLE
problems using cifs and nfs netshare volumes simultaneously

### ISSUE THREAD

**Issue by pimpim** [gondor/docker-volume-netshare#4]
I started two instances of docker volume netshare 

`~$ sudo ls -l /run/docker/plugins`
`total 0`
`~$ sudo service docker-volume-netshare start`
` * Starting Docker-Volume-Netshare: docker-volume-netshare               [ OK ] `
`~$ sudo ls -l /run/docker/plugins`
`total 0`
`srw-rw---- 1 root root 0 Nov  9 13:56 nfs.sock`
`~$ sudo service docker-volume-netshare-cifs start`
` * Starting Docker-Volume-Netshare: docker-volume-netshare-cifs          [ OK ] `
`~$ sudo ls -l /run/docker/plugins`
`total 0`
`srw-rw---- 1 root root 0 Nov  9 13:56 cifs.sock`
`srw-rw---- 1 root root 0 Nov  9 13:56 nfs.sock`

Now I can start a docker with either nfs or cifs just fine ... 

`docker run -i -t --rm  --volume-driver=cifs -v cifs/foo:/foo ubuntu /bin/bash`
works fine and
`docker run -i -t --rm --volume-driver=nfs -v nfs/bar:/bar  ubuntu /bin/bash`
works fine 

But if I do: 
`docker run -i -t --rm  --volume-driver=cifs -v cifs/foo:/foo --volume-driver=nfs -v nfs/bar:/bar  ubuntu /bin/bash`

I get: 

`Error response from daemon: Cannot start container d74c269f9696236c522678ea6234921a6a83af5424331e6fb999b4ca7d74500e: Plugin Error: VolumeDriver.Mount, {"Mountpoint":"","Err":"exit status 32"}`

**Comment by gondor** [comment]
This currently is a limitation with the existing Docker daemons.  Docker is extending these capabilities in future releases.   See my comments on Issue #3 which would allow us to get past this in the existing Docker releases.

**Comment by gondor** [comment]
@pimpim If you upgrade to `Docker 1.9.0` and re-download the latest binary of `docker-volume-netshare` you can do the new approach which was introduced in 1.9.0+ of Docker.

```
docker run -d \
    -v $(docker volume create --driver=nfs --name=nfs/bar):/bar \
    -v $(docker volume create --driver=cifs --name=cifs/share --opt username=user --opt password=pass --opt domain=domain):/somewhere \
    my image
```

**Comment by gondor** [comment]
Re-open if problem still persists
