### ISSUE TITLE
cifs password shows on command line

### ISSUE THREAD

**Issue by etlweather** [gondor/docker-volume-netshare#5]
It would be preferable if the password for the CIFS connection wouldn't show on the command line in the process list. Could use `netrc` or other configuration mechanism.

**Comment by gondor** [comment]
Ok .netrc support has been example.  See the project README for examples.   Binaries have been updated as well and links within README.  Let me know.

**Comment by etlweather** [comment]
Sorry for taking so long to try this out! Thank you for doing this. It works. I only run into one relatively small problem - if there is a `#` sign in the password, the `.netrc` input is truncated at that point. So if I have password: `test1234#34556` - it will use password `test1234`.

I tried escaping the `#` with a `\` and that didn't do it.
