### ISSUE TITLE
On go build, 'cannot find package "github.com/docker/docker/pkg/sockets"'

### ISSUE THREAD

**Issue by jordancrawfordnz** [gondor/docker-volume-netshare#6]
When I try and build docker-volume-netshare I get the message:
``../calavera/dkvolume/tcp_listener.go:9:2: cannot find package "github.com/docker/docker/pkg/sockets"``.

https://github.com/docker/docker/commit/8e034802b7ad92a29f08785e553415adcd1348a3 has removed ``github.com/docker/docker/pkg/sockets`` just a day ago.

I notice https://github.com/calavera/dkvolume isn't maintained anymore, with https://github.com/docker/go-plugins-helpers/tree/master/volume to be used instead.

I'm new to Go. Presumably there is some way to use an older version of one of these dependancies or maybe go-plugins-helper uses docker/go-connections as the docker commit above mentions.

**Comment by gondor** [comment]
Thanks for reporting this.  This is the one gotcha with go when upstream sources change.  New dependencies have been switched out and it's building now.  Let me know if this fixes your issue.

**Comment by jordancrawfordnz** [comment]
Awesome! That solved it.
