### ISSUE TITLE
CIFS with volume management only uses credentials once

### ISSUE THREAD

**Issue by jordancrawfordnz** [gondor/docker-volume-netshare#7]
If I make a CIF's volume using the Docker 1.9.0+ way, i.e.: like ``$ docker volume create -d cifs --name cifshost/share --opt username=user --opt password=pass --opt domain=domain``, the first container I launch with this volume runs fine.

If I stop this container and start another one using the same command, the ``--verbose`` option reveals it is attempting to connect as a guest so gets a permission denied error.
I have tried using ``docker rm`` on the first container before starting the second but this doesn't make any difference.

If I define credentials as arguments to ``docker-volume-netshare`` it works fine every time. I'm not sure if this might relate to https://github.com/gondor/docker-volume-netshare/issues/4 - I'm guessing the suggested way of creating volumes on ``docker run`` would resolve this issue.

**Comment by gondor** [comment]
I'll have to re-test this week.  When I originally wrote this feature and tested it this wasn't an issue.   Is netshare running the whole time starting from when `docker volume create` was issued until your 2nd container attempt?

**Comment by jordancrawfordnz** [comment]
Hmm. I just re-tried this and couldn't make the issue happen again!

I'm pretty sure was running with the same netshare instance running on the second container attempt but I noticed the same thing happens when you do close down the netshare instance and try launch a container with the volume.

At this stage I'm thinking this is something specific to my setup at the time (was also having lots of problems getting volumes to mount). For future reference, I'm on Docker 1.9.0 on a Raspberry Pi with HypriotOS.

**Comment by gondor** [comment]
Keep an eye on it.  I seem to recall a slight flaw with Docker where they only send the credentials to the volume plugins on the initial create.  If the plugin gets shutdown they lose the context.  You would "think" docker would preserve the credentials and send them on the actual mount command.  I'd have to retest but I seem to recall I thought the pattern was odd at the time.    If Docker has reasons why they do this then I could look into some sort of an on disk cache to keep the state and reload it on a relaunch of netshare.
