### ISSUE TITLE
.netrc in a different location when running from init.d

### ISSUE THREAD

**Issue by jordancrawfordnz** [gondor/docker-volume-netshare#9]
It seems as though the $HOME variable isn't set when doing ``service docker-volume-netshare start``, so  when running from the root user manually the .netrc file must be in ``/root/.netrc``, and when running from init.d it must be in ``/.netrc``.

Obviously its just a small annoyance, but maybe it could just always be located at ``/.netrc`` or allow the .netrc path to be provided as a command line argument?

**Comment by gondor** [comment]
@jordancrawfordnz  I like your second option of making it a command line argument.  By default we should resort to $HOME so we don't break existing functionality but add the command line option so the init scripts can use it.  Did you want to add this or do you want me to do it?

**Comment by jordancrawfordnz** [comment]
If you had a chance to add this it would be great. I can have a look in a few days though if you're busy.

**Comment by gondor** [comment]
@jordancrawfordnz support has been added.  The commit above may look deceiving as its 1 commit before the merge of your recent security addition.  Let me know if this resolves your scenario.

**Comment by jordancrawfordnz** [comment]
Awesome. I'll give this a try in the weekend.

**Comment by jordancrawfordnz** [comment]
@gondor: Thanks, this works.
